[versions]
lombok = "1.18.36"
junit-jupiter = "5.11.4"
hamcrest = "2.2"
discord4j = "3.3.1"
sentry = "8.34.1"
log4j = "2.25.3"

[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
discord4j = { group = "com.discord4j", name = "discord4j-core", version.ref = "discord4j" }
sentry = { group = "io.sentry", name = "sentry", version.ref = "sentry" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
log4j-slf4j2 = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4j" }
